# Generated by Django 3.2.9 on 2021-11-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobs',
            managers=[
            ],
        ),
    ]
