# Generated by Django 3.2.9 on 2021-12-07 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('marked_jobs', models.ManyToManyField(to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                           related_name='studentprofile_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
