# Generated by Django 3.2.9 on 2021-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('marked_jobs', models.ManyToManyField(to='jobs.Job')),
            ],
        ),
    ]
